// <auto-generated />
using System;
using DemoApp.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApp.Api.Migrations
{
    [DbContext(typeof(DemoAppDBContext))]
    [Migration("20221202155420_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoApp.Data.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreationTrackingUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeleteTrackingUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdateTrackingUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7fe7458-b047-400f-ae5a-d11c3363e76f"),
                            CreationDate = new DateTime(2022, 12, 2, 16, 54, 20, 863, DateTimeKind.Local).AddTicks(8796),
                            CreationTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            FirstName = "Hazard",
                            LastName = "Eden",
                            UpdateTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("7305d300-6db2-4998-942f-4becb924917c"),
                            CreationDate = new DateTime(2022, 12, 2, 16, 54, 20, 863, DateTimeKind.Local).AddTicks(8796),
                            CreationTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            FirstName = "Hazard",
                            LastName = "Thorgan",
                            UpdateTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("3b13455d-38c9-40c6-a3da-1a229a68ed96"),
                            CreationDate = new DateTime(2022, 12, 2, 16, 54, 20, 863, DateTimeKind.Local).AddTicks(8796),
                            CreationTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            FirstName = "Hazard",
                            LastName = "Kylian",
                            UpdateTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("778f76b2-bbc2-41c0-8ddb-30d7c95eafc1"),
                            CreationDate = new DateTime(2022, 12, 2, 16, 54, 20, 863, DateTimeKind.Local).AddTicks(8796),
                            CreationTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            FirstName = "Mpenza",
                            LastName = "Emile",
                            UpdateTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d693862f-5b0c-45b2-a494-17e9d61832e7"),
                            CreationDate = new DateTime(2022, 12, 2, 16, 54, 20, 863, DateTimeKind.Local).AddTicks(8796),
                            CreationTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            FirstName = "Mpenza",
                            LastName = "Mbo",
                            UpdateTrackingUserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
